### ISSUE TITLE
Content size is too high

### ISSUE THREAD

**Issue by ciryon** [evgenyneu/Auk#1]
I think I'm using Auk as intended and have instantiated a UIScrollView from my storyboard. I have used 

``self.scrollView.auk.show(image: downloadedImage)``

to set images. The problem is that content size is too high so that the images can be dragged vertically. When the first image is loaded a blank space above the image is visible. Please see attached screenshot.
![contentsize_problem](https://cloud.githubusercontent.com/assets/151225/9581204/45018568-4ffe-11e5-88a7-a6635fdd6591.png)
 The bottom part of the image is not visible, but at the top it's black (the UIScrollView background color).

Anything I'm doing wrong or is this a bug?

**Comment by evgenyneu** [comment]
Hi, interesting, do you have all constraints setup on the scroll view? It looks like the layout is having problem with its height.

* Try adding a height constraint and see what happens.
* Check if you have warnings/errors in the storyboard.
* Check the Output window for Auto Layout errors during the run.
* Also try clearing the **Adjust Scroll View Insets** checkbox in the *Attribute Inspector* of your View Controller.

Let me know how it goes.

**Comment by ciryon** [comment]
"Also try clearing the Adjust Scroll View Insets checkbox in the Attribute Inspector of your View Controller."

Wow, thanks, that did the trick!

**Comment by evgenyneu** [comment]
Glad it worked for you, @ciryon. I will put the note about "Adjust Scroll View Insets" in the readme.
