### ISSUE TITLE
Update image on existing page

### ISSUE THREAD

**Issue by eyaldar** [evgenyneu/Auk#12]
Is there a way to update the currently displayed image on a certain page?
I've seen in the code that you can change the image using the AukPage's code itself but it seems that there is no way to access the pages or fetch one particular page after it's been added easily.

Am I missing something?

**Comment by evgenyneu** [comment]
Hello @eyaldar, 

Yes you are right, the [AukPage](https://github.com/evgenyneu/Auk/blob/master/Auk/AukPage.swift) is an internal class and is not accessible at the moment. Could you describe your use case, how would it look from user's perspective? 

Thank you

**Comment by eyaldar** [comment]
A carousel with 3 pictures where tapping on a picture will open an image picker to choose picture for the current page.

**Comment by evgenyneu** [comment]
One way to achieve that currently would be:

1. First, find out the current page index: `scrollView.auk.currentPageIndex`
1. Then, remove all images: `scrollView.auk.removeAll()`
1. Add images again: `scrollView.auk.show`
1. Finally, scroll to the page that was displayed before: `scrollView.auk.scrollTo(2, animated: false)`

Maybe we could add two methods to the library to make it easier: `scrollView.auk.removeAt(index: 3)` and `scrollView.auk.showAt(image: image, index: 3)`.

**Comment by evgenyneu** [comment]
And, in addition to `removeAt` and ` showAt` we could add a shortcut method `scrollView.auk.updateAt(image: image, index: 3)`. What do you think?

**Comment by eyaldar** [comment]
I think that removeAt, showAt and updateAt would be great.

**Comment by evgenyneu** [comment]
Alright, I will do that when I have a moment (which may not be very soon because I am writing a long math assignment now). Thank you for raising the issue.

**Comment by eyaldar** [comment]
Thank you very much for the snappy response!

**Comment by evgenyneu** [comment]
@eyaldar, did your pull request do the job?

**Comment by eyaldar** [comment]
It did, thanks for your help!

**Comment by evgenyneu** [comment]
Thanks for your contribution, it will be useful to others.
