### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by J-phantom** [evgenyneu/Auk#14]
I use of plugin you. when the program start  This error ,  "Thread 1:EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)”  in line  var value = Int(round(offset / width))

can you help me ?
i'm beginner in iOS programming.
thanks

**Comment by evgenyneu** [comment]
Hi @J-phantom, this does not sound good. Could you isolate this bug in a demo app and attach the project here so I can have a look?

**Comment by J-phantom** [comment]
sure . please wait

**Comment by evgenyneu** [comment]
You can zip it and just attach here by dragging the file it into the message box. If you don't want iother people to see it you can email me: sausageskin at gmail

**Comment by J-phantom** [comment]
email sent to you sausageskin@gmail.com

**Comment by evgenyneu** [comment]
Closing this for now. @J-phantom, feel free to reopen it if needed.
