### ISSUE TITLE
Supplying complete XCode demo project

### ISSUE THREAD

**Issue by santanu4ver** [evgenyneu/Auk#15]
Hello,

Is it possible to supply a complete (working) XCode project to "Demo"? I think that would be very easy for many like me to just jump into the project source and give a run. At present I'm struggling just to run the supplied demo project. 

Thanks.

**Comment by evgenyneu** [comment]
Hi @santanu4ver, what is the Xcode version you are using. I have recently upgraded the project for Xcode 7.3. That might be causing your problem.

If you need to run the demo on Xcode 7.2 you can try the `2.0.19` tag.

```
git checkout -b xcode_7.2 2.0.19
```

Let me know if it helps.

**Comment by santanu4ver** [comment]
Thank you. I have XCode 7.2. Unlike any complete project, and I able to run the demo as well now.
