### ISSUE TITLE
click response

### ISSUE THREAD

**Issue by zigool** [evgenyneu/Auk#2]
hi.
i have 3 image loaded from web
how i can detect which image is tapped?!
i'm beginner in iOS programming.
thanks

**Comment by evgenyneu** [comment]
Hi, here is what you need to do to add an image tap handler to the scroll view.

1. In the Storyboard drag a *Tag Gesture Recognizer* into your scroll view.
1. Show assistant editor with your view controller code.
1. Do the control-drag from the tap gesture recognizer in the storyboard into your view controller code.
1. A dialog will appear, change the *Connection* to *action* and enter the name of the method.
1. This method will be called when the scroll view is tapped. Use the `auk.currentPageIndex` property of your scroll view to get the index of the current page.

I have updated the demo app with the tap example.

<img width="350" alt="Adding a connection for tap handler" src="https://cloud.githubusercontent.com/assets/880411/10561535/61e883b2-7578-11e5-8d28-5f0c82bfac6c.png">

**Comment by evgenyneu** [comment]
@zigool did my solution work for you?

**Comment by zigool** [comment]
yes
you solved my problem!
thanks man

**Comment by evgenyneu** [comment]
Cool, I am glad it worked for you.
