### ISSUE TITLE
Scroll not working

### ISSUE THREAD

**Issue by J-Arji** [evgenyneu/Auk#22]
hello evgeny
I have an array that has three address 
`{...,"ImageAddress":["/Images/HotelImages/Parl-orumie.jpg","/Images/HotelImages/NULLradison_blue.jpg","/Images/HotelImages/safaeie.jpg"],... }`

 read json and save image in 
`imagesHotel : [String] = ["/Images/HotelImages/Parl-orumie.jpg","/Images/HotelImages/NULLradison_blue.jpg","/Images/HotelImages/safaeie.jpg"]
`
```

override func viewDidLoad() {

        super.viewDidLoad()
        implementation()
        Scrollable.createContentView(contentScrollView)
        scrollView.delegate = self
        scrollView.auk.settings.placeholderImage = UIImage(named: "1.png")
        scrollView.auk.settings.errorImage = UIImage(named: "1.png")
            self.HotelData() // json data 
            
        
                // Add segments

    }
```
When I want to show my photos and scroll , but scroll Does not work

 /```
/ image show
    func imageshow(){
        scrollView.auk.removeAll()
        print(imagesHotel)
        for image in  imagesHotel {
            print(image)
            let url =  "\(remoteImageBaseUrl)\(image)"
            scrollView.auk.show(url: url)
           
            
        }
        scrollView.auk.startAutoScroll(delaySeconds: 3.0)
    
        
        
    }
```

**Comment by evgenyneu** [comment]
Hi @J-phantom. Does it show the images in the scroll view?

**Comment by J-phantom** [comment]
yeah it's show

**Comment by evgenyneu** [comment]
Your code example looks good. I have made a demo app for you that shows remote images and starts auto scroll. Let me know how it goes.

[autoscroll_auk_demo.zip](https://github.com/evgenyneu/Auk/files/239972/autoscroll_auk_demo.zip)

**Comment by J-Arji** [comment]
thank @evgenyneu 👍
