### ISSUE TITLE
Add Titles

### ISSUE THREAD

**Issue by classified** [evgenyneu/Auk#23]
How to add titles above image ?

**Comment by evgenyneu** [comment]
Hi, I need more information. Can you give an example of what you want to achieve in your app from the user's perspective?

**Comment by classified** [comment]
Hello There,

I have a banner which contains Remote Images and it does auto scroll.

What i want is that I want a Title or Label over the Image, so i can display the names of images.

**Comment by evgenyneu** [comment]
Thanks for explaining, it makes sense now. Nice app design, by the way. There are two ways of doing it: inside and outside of the scroll view.


### Inside the scrollview

If you want the text to scroll with the images then it can not be done with Auk rout of the box. You will need to fork the library and extend it for your needs. 

Each page in the scroll view is an instance of the [AukPage](https://github.com/evgenyneu/Auk/blob/master/Auk/AukPage.swift) class which is a UIView subclass. Therefore, one can add subviews to the pages but Auk currently does not expose the pages to the public.

Here is what you can do in the forked version of the Auk:

- Create a new public `pages` property in the [Auk]( https://github.com/evgenyneu/Auk/blob/master/Auk/Auk.swift) class that returns the array of `AukPage` objects by calling the `AukScrollViewContent.aukPages(scrollView)` function.
- Make `AukPage` class public.
- In your app, after you added the remote images, add the labels to each of the pages and position it with auto layout.

### Outside the scrollview

Or, if you want the label to be outside of the scroll view, then you can see how it is done in the demo app. There the label is stationary under the scroll view and shows the author's name for the currently visible page.

**Comment by classified** [comment]
I have added UILabel onto the ImageView. Thank you for your help if you want to integrate in your library i can PR it.

**Comment by evgenyneu** [comment]
I think the label is a bit specific customization, I would leave it out of the library for now. Thank you for your feedback.
