### ISSUE TITLE
Image Size Issue

### ISSUE THREAD

**Issue by Abd5353** [evgenyneu/Auk#26]
Hi,

I am having an issue where the imageView in the scrollView is smaller than it should be. I created a test image to test it and the test image ends up being bigger then the scroll view's image. I need the image in the scroll view to be like the test image. The scrollView and the testImage's sizes are the same.

Here is my code:

```
scrollViewSlider.auk.settings.contentMode = UIViewContentMode.ScaleAspectFit
testImage.contentMode = UIViewContentMode.ScaleAspectFit
scrollViewSlider.auk.show(image: screenShot)
testImage.image = screenShot
```

Here is the result:

![simulator screen shot may 23 2016 2 56 14 pm](https://cloud.githubusercontent.com/assets/6297642/15481048/9e1d5568-20f6-11e6-913b-2b74da223aee.png)

Thanks!

**Comment by evgenyneu** [comment]
Hi, this is very weird indeed. What happens if you use
 ScaleAspectFill?

**Comment by Abd5353** [comment]
@evgenyneu The test image remains the same but the scrollView image disappears:

![simulator screen shot may 23 2016 7 23 03 pm](https://cloud.githubusercontent.com/assets/6297642/15487534/1d54c99a-211c-11e6-9fad-2309099b591d.png)

**Comment by evgenyneu** [comment]
Very interesting, can you isolate this problem into a demo app and attach it here? I will have a look. Thanks.

**Comment by Abd5353** [comment]
Hi,

No worries, I got it to work! There was a problem with the image but now its working.

Thanks!
