### ISSUE TITLE
Objects over scrollview

### ISSUE THREAD

**Issue by danielpassos** [evgenyneu/Auk#27]
Is possible to put a label over the scrollview?

**Comment by evgenyneu** [comment]
Hi again, Do you want each image of the scroll view to have a separate label which will scroll along with the image?

**Comment by danielpassos** [comment]
Hi @evgenyneu 

I want to have a label and change de text when image change, like what the demo app has, _but_ I want that label _over_ the scrollview. Something like it

![2016-05-29 21-54-20](https://cloud.githubusercontent.com/assets/13337/15637124/2745d5c2-25e8-11e6-9553-1e2e5d799ad5.png)

But when I added that, it scrolled (and disappear) with the first image :(

**Comment by evgenyneu** [comment]
Oh, I see, I think this is doable, you need to make sure you add your label to the main view and NOT to the scroll view. After that, you can position the label with auto layout to make it overlap with the scroll view.

Now that we have an overlay label over the scroll view it may prevent from scrolling the scroll view. You will need to forward the touch events from the label to the scrollview underneath. A solution for it is discussed here: http://stackoverflow.com/questions/3834301/ios-forward-all-touches-through-a-view

**Comment by danielpassos** [comment]
@evgenyneu Thanks for the link.
