### ISSUE TITLE
How to add image descriptions in slideshow?

### ISSUE THREAD

**Issue by JEKos** [evgenyneu/Auk#36]
Hi,
How can I add image descriptions in slideshow?
Can you add  the implementation on README?
I know, you have it already on your Demo, but I want to drag a Strings from Parse server to display them as Image Descriptions in my slideshow, and on your Demo is only for local.

**Comment by evgenyneu** [comment]
Hi @JEKos, do you want the image description label to be inside the scrollview so it is scrolled together with the image? Or do you want the label to be motionless and be outside the scrollview?

Yes, good idea about writing a tutorial in the readme, I will do that when I have a spare moment.

Can you explain what do you mean by "drag a Strings from Parse server". What is Parse server? And what do you mean by "drag Strings"?

Thanks

**Comment by JEKos** [comment]
Description inside the scrollview, I have already done it, the only thing I want now is how the image descriptions works on your demo, so to do the connection it with Array of String from the backend server.

Parse server is a backend server ,  you can store strings,files,bool etc.

**Comment by evgenyneu** [comment]
Ok, a question. Do you have multiple labels in the scrollview (one label for every page)? Or do you have a single label that is displayed on top of the scrollview and does not move with the pages?

I did not know about the parse server, thanks for that.

**Comment by JEKos** [comment]
One Label, with blur effect behind, at the bottom of the slideshow, and I don't know how to make it to recognize when the image change with autoscroll, so to change the label too.

**Comment by evgenyneu** [comment]
Oh, I see now, thanks for explaining. There is a wiki page that shows how to update a label when the page is changed in the scroll view:

https://github.com/evgenyneu/Auk/wiki/Detect-page-scrolling

**Comment by evgenyneu** [comment]
Hi @JEKos, did the method I described work for you?

**Comment by JEKos** [comment]
Hi,
Sorry for the delay,
I tested quickly but I had an error, I'm gonna test it again and I'll send you here to know, but I think this is not gonna work when autoscroll is enable

**Comment by evgenyneu** [comment]
No stress, @JEKos. Don't hesitate to ask a question if Auk is not working for you.

**Comment by RanjitKadam** [comment]
@evgenyneu , how to add description inside scrollView ?

**Comment by evgenyneu** [comment]
Hi again @RanjitKadam, do you want each image of the scroll view to have its own description that will be scrolled along with the image?

**Comment by RanjitKadam** [comment]
@evgenyneu  yes, I want it to scroll with Image.

**Comment by RanjitKadam** [comment]
@evgenyneu @JEKos can you help me out with this?

**Comment by evgenyneu** [comment]
@RanjitKadam, the Auk library does not currently allow to add subviews (like labels) to the individual pages, so they can scroll with the images. However, you can fork the library add add the labels yourself. Each page in the scroll view is an object of class [AukPage](https://github.com/evgenyneu/Auk/blob/master/Auk/AukPage.swift). If you add a label to the auk page it will scroll along with it.

**Comment by JEKos** [comment]
I did not make it, I'm gonna find another way. 
You can close the issue.

**Comment by evgenyneu** [comment]
Closing the issue for now, feel free to reopen when needed.
