### ISSUE TITLE
Runtime Error: Library not loaded

### ISSUE THREAD

**Issue by gadget00** [evgenyneu/Auk#37]
Hi evgenyneu,

Im using version 2.0.19 right now, and my app compiles correctly. But now I have this runtime error as soon as the app loads in the simulator: `dyld: Library not loaded: @rpath/Auk.framework/Auk
  Referenced from:XXXXX   Reason: image not found`

This never happened to me. I installed Auk through Cocoapods, and tried to re-create the pods 4 times already, including using 'pod deintegrate' to totally eliminate Pods from my project and re-creating them again, and still get this error.

please help.

**Comment by evgenyneu** [comment]
Hi @gadget00 , I think I saw this problem before but do not remember how exactly I fixed it.
I am sure you already tried this, but if not, here is what I usually do:

```
rm -rfd ~/Library/Developer/Xcode/DerivedData/*
rm -rfd ~/Library/Caches/com.apple.dt.Xcode/*
```

If this does not help, try "Reset content and settings" in the Simulator menu.
On physical device, try uninstalling the app.

Let me know how it goes.

**Comment by gadget00** [comment]
Fixed problem; thanks for the tip!

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
