### ISSUE TITLE
Just a little Typo..

### ISSUE THREAD

**Issue by agent-reed** [evgenyneu/Auk#39]
In your README.md file under the section Respond to User Tap you write:

> In the Storyboard drag a Tag Gesture Recognizer into your scroll view.

I think you mean "**Tap**"

**Comment by evgenyneu** [comment]
Thank for spotting the typo!  🖖

**Comment by evgenyneu** [comment]
Closing this for now. Please feel free to reopen if you notice other typas. 🙂
