### ISSUE TITLE
Disable Image Dragging

### ISSUE THREAD

**Issue by alaxicsmith** [evgenyneu/Auk#4]
I'm using AUK and everything is working perfect, but is there a way to disable images being draggable in views?

**Comment by evgenyneu** [comment]
Hi, sorry what do you mean by dragging? Do you mean that you want to disable the scroll view from scrolling the images from side to side?

**Comment by alaxicsmith** [comment]
@evgenyneu In the view where the slideshow is, I can move the image around in it's container.

**Comment by evgenyneu** [comment]
Hmm, that should not be happening. Did you clear "Adjust scroll view insets" for the view controller?

<img width="463" alt="adjust_table_view_insets" src="https://cloud.githubusercontent.com/assets/880411/11198226/59d883b4-8d17-11e5-95af-bdbb5ff6d7c1.png">

**Comment by alaxicsmith** [comment]
Ah, that was the issue. I thought I had done with the initial set up, but I'm guessing I glanced over. Thanks!

**Comment by evgenyneu** [comment]
No worries, have a good day.
