### ISSUE TITLE
Crash App

### ISSUE THREAD

**Issue by J-Arji** [evgenyneu/Auk#40]
Hello @evgenyneu 

When I run the app with the iPhone 4s and iPhone 5 gives this error :
```
"(extension in Auk):__ObjC.UIScrollView.auk.getter : Auk.Auk", referenced from:
      balen.MainViewController.(currentImageDescription in _6D33176B14C9C200DCC5C77F42099FC9).getter : Swift.String? in MainViewController.o
      balen.MainViewController.implementation () -> () in MainViewController.o
      balen.MainViewController.imageshow () -> () in MainViewController.o
      balen.MainViewController.viewWillTransitionToSize (__C.CGSize, withTransitionCoordinator : __ObjC.UIViewControllerTransitionCoordinator) -> () in MainViewController.o
      balen.MainViewController.willRotateToInterfaceOrientation (__C.UIInterfaceOrientation, duration : Swift.Double) -> () in MainViewController.o
      balen.MainViewController.(viewWillTransitionToSize (__C.CGSize, withTransitionCoordinator : __ObjC.UIViewControllerTransitionCoordinator) -> ()).(closure #1) in MainViewController.o`
```
and 
```
type metadata accessor for Auk.Auk", referenced from:
      balen.MainViewController.implementation () -> () in MainViewController.o
```
Because you know it?

**Comment by evgenyneu** [comment]
Hi @J-Arji, I do not know why it crashes based on the information you provided. I can see some kind of stack trace but not an actual error. Is that all the error text that you receive? If not, can you paste the whole error text ?

**Comment by J-Arji** [comment]
whole error :
`  "(extension in Auk):__ObjC.UIScrollView.auk.getter : Auk.Auk", referenced from:
      balen.MainViewController.(currentImageDescription in _6D33176B14C9C200DCC5C77F42099FC9).getter : Swift.String? in MainViewController.o
      balen.MainViewController.implementation () -> () in MainViewController.o
      balen.MainViewController.imageshow () -> () in MainViewController.o
      balen.MainViewController.viewWillTransitionToSize (__C.CGSize, withTransitionCoordinator : __ObjC.UIViewControllerTransitionCoordinator) -> () in MainViewController.o
      balen.MainViewController.willRotateToInterfaceOrientation (__C.UIInterfaceOrientation, duration : Swift.Double) -> () in MainViewController.o
      balen.MainViewController.(viewWillTransitionToSize (__C.CGSize, withTransitionCoordinator : __ObjC.UIViewControllerTransitionCoordinator) -> ()).(closure #1) in MainViewController.o
  "type metadata accessor for BSDropdown.BSDropdown", referenced from:
      type metadata accessor for BSDropdown.BSDropdown! in TrainSearchView.o
      type metadata accessor for BSDropdown.BSDropdown! in AircraftSearch.o
  "type metadata accessor for AnimatedSegmentSwitch.AnimatedSegmentSwitch", referenced from:
      type metadata accessor for AnimatedSegmentSwitch.AnimatedSegmentSwitch! in LogInViewController.o
      balen.DetailCityTableViewController.(navBarSegmentSwitch in _36868BC65D4CDC617C61330C9F024C60).getter : AnimatedSegmentSwitch.AnimatedSegmentSwitch in DetailCityTableViewController.o
      balen.DetailCityTableViewController.((navBarSegmentSwitch in _36868BC65D4CDC617C61330C9F024C60).getter : AnimatedSegmentSwitch.AnimatedSegmentSwitch).(closure #1) in DetailCityTableViewController.o
      type metadata accessor for AnimatedSegmentSwitch.AnimatedSegmentSwitch? in DetailCityTableViewController.o
  "type metadata accessor for Auk.Auk", referenced from:
      balen.MainViewController.implementation () -> () in MainViewController.o
  "protocol descriptor for BSDropdown.BSDropdownDelegate", referenced from:
      l_protocol_conformances in TrainSearchView.o
      l_protocol_conformances in AircraftSearch.o
      l_protocol_conformances in TrainSearchView.o
      l_protocol_conformances in AircraftSearch.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
[http://uploads.im/mFa9Z.jpg](image error)

**Comment by evgenyneu** [comment]
Hi @J-Arji, I have no idea why you have the build errors. If would google the error "undefined symbols for architecture i386" and see what solutions are there.

**Comment by J-Arji** [comment]
I do not know what the problem was But when the pod file is deleted and re-installed the problem was solved

thank for help :)

**Comment by evgenyneu** [comment]
No worries, thanks for sharing the information with others.
