### ISSUE TITLE
Changing Podfile doesn't update the code for Swift 3; keep getting error in Xcode

### ISSUE THREAD

**Issue by gadget00** [evgenyneu/Auk#51]
I'm migrating my dev environment to Xcode 8 and Swift 3.   According to Xcode, the Auk and moa code aren't updated to Swift 3 and it keeps asking me to "upgrade the source".  I followed the new instructions, deleted all the podfile.lock, the pod folder and also the .xcworkspace file and generated everything again from the terminal; still no luck.

Am I doing something wrong or missing something??

Thank you

**Comment by evgenyneu** [comment]
Hello @gadget00, thanks for reporting. This is very strange indeed. If you updated moa and Auk to the recent versions mentioned in the README than CocoaPods should either update them or show an error. I have created a new project in Xcode 8.1 with Auk and Moa and it works fine. Could you attach a screenshot of your error(s) please?

[UsingMoa.zip](https://github.com/evgenyneu/Auk/files/585036/UsingMoa.zip)

**Comment by gadget00** [comment]
Somehow after opening your project (it opened without any error), I again recreated all the pod files and now they are fine.  We can close this.  Here is a screenshot of my podfile and the pod instal output, just for checking.  I'm still working on some code (some Google Places stuff that is not working now) but the warning page doesn't show up anymore.  Would it be corrected now?

Thanks for the quick response

![screen shot 2016-11-11 at 2 05 28 pm](https://cloud.githubusercontent.com/assets/27822/20228734/b3795c5c-a820-11e6-8ba7-453012efcdc2.png)
![screen shot 2016-11-11 at 2 20 07 pm](https://cloud.githubusercontent.com/assets/27822/20228739/c103d78a-a820-11e6-8748-4f33822196bb.png)

**Comment by evgenyneu** [comment]
I am glad that the problem solved itself. I do not know what it was. Nice color scheme, by the way. Thanks for reporting, anyway, and good luck updating the rest of your project to Swift 3.

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
