### ISSUE TITLE
Turn Slideshow to Full Screen on Portrait and Landscape

### ISSUE THREAD

**Issue by bertadevant** [evgenyneu/Auk#53]
Hi, 

Love the library, It allows me to control each slides and that is exactly what I needed! Thanks :) 

Is there a way to get the slideshow to show up on full screen if tapped?

**Comment by evgenyneu** [comment]
Hi @bertadevant, good question, I've never used the full screen personally, but here is a solution I found:

```Swift
class ViewController: UIViewController {  
  override var prefersStatusBarHidden: Bool {
    get {
      return true;
    }
  }
}
```

It looks like there are other ways of doing it describe in [this StackOverflow page](http://stackoverflow.com/questions/620386/iphone-how-to-create-a-full-screen-app).
 
![auk_full_screen](https://cloud.githubusercontent.com/assets/880411/20500127/599a29c6-b088-11e6-9bc7-6f3dac2d5da0.gif)

Here is a demo project:

[UseAuk.zip](https://github.com/evgenyneu/Auk/files/604733/UseAuk.zip)

Let me know how it works for you.

**Comment by bertadevant** [comment]
Thanks :) 

One quick thing though, when I use scrollToPage() it goes through all the slides, one after the other until it finds the one I was asking for. Is there a way to just show that one? Without the "transition"?

**Comment by evgenyneu** [comment]
Yes, there is an optional `animated` argument. If you set it to `false` it will switch to the page without animation.

```Swift
scrollView.auk.scrollToPage(atIndex: 2, animated: false)
```

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
