### ISSUE TITLE
is video supportable???

### ISSUE THREAD

**Issue by heavyBug** [evgenyneu/Auk#57]
can i mix images with videos in this slider..? if yes then how?

**Comment by evgenyneu** [comment]
Hello @heavyBug, Auk does not support videos, unfortunately.

**Comment by heavyBug** [comment]
Then Kindly suggest me a reasonable library ...

**Comment by evgenyneu** [comment]
Sure, there is a list of alternative solutions [in the readme](https://github.com/evgenyneu/Auk#alternative-solutions), but I am not sure if any of them supports videos. Sorry.

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
