### ISSUE TITLE
Is it possibile to disable manual scrolling?

### ISSUE THREAD

**Issue by tmichele** [evgenyneu/Auk#58]
I would like to disable manual scrolling, is it possible?

Thanks for the great work,
Michele

**Comment by evgenyneu** [comment]
Thanks, @tmichele. Yes, I think you can do it by disabling *"User interaction enabled"* property of the scroll view in the *Attributes inspector*. Let me know if it works for you.

<img width="701" alt="auk_disable_user_interaction" src="https://cloud.githubusercontent.com/assets/880411/23106819/5414bda8-f747-11e6-830d-fd28dd0a93fc.png">

**Comment by saysayshee** [comment]
thank, it work for me 👍

**Comment by evgenyneu** [comment]
Great, I am glad it helped. Good luck!
