### ISSUE TITLE
ScrollView's height will increase when autoscrolling

### ISSUE THREAD

**Issue by ivanstang** [evgenyneu/Auk#59]
I added 2 images to the scrollview and let it autoscrolling.
I found that when it scroll to the second image, the scroll view's height was increased about 1px automatically. Of cause, these 2 images have the same size.
If I add a third image to the scrollview, it will be shown in right size.

Does anyone encounter the same issue?

**Comment by ivanstang** [comment]
Remark: Just the second image has the issue!

**Comment by evgenyneu** [comment]
Hi @ivanstang, thanks for reporting. Could you attach the images here so I can try to reproduce this issue?

**Comment by evgenyneu** [comment]
Hi @ivanstang, was this issue fixed? Thanks.

**Comment by ivanstang** [comment]
No, it's not a serious issue, so I ignored it.


发自我的 iPhone

**Comment by evgenyneu** [comment]
Cool, thanks. Closing the issue then. Feel free to reopen if needed.
