### ISSUE TITLE
Install Auk and moa in cocoaps

### ISSUE THREAD

**Issue by HideCode7** [evgenyneu/Auk#63]
I install Auk an moa in cocoaps pods like this 

use_frameworks!

target 'projectName' do
pod 'moa', '~> 8.0'
pod 'Auk', '~> 7.0'
pod 'Alamofire', '~> 4.0'
pod 'PayPal-iOS-SDK', '~> 2.12.0'
end

but i have a two errors 
Framework not found moa
Framework not found Auk

**Comment by evgenyneu** [comment]
Hi @HideCode7, thanks for reporting. This is puzzling and I don't know why you are getting this error. Your podfile looks fine to me. I created a new demo app that uses moa and Auk with CocoaPods, please find attached. Let me know if it helps.


[UsingUsing.zip](https://github.com/evgenyneu/Auk/files/945681/UsingUsing.zip)

**Comment by HideCode7** [comment]
My bad, because i forgot to add Embedded Binaries. Congratz to goos jog :) thank you

**Comment by evgenyneu** [comment]
Closing. Feel free to reopen if needed.
