### ISSUE TITLE
Support GIF ?

### ISSUE THREAD

**Issue by shanmarkus** [evgenyneu/Auk#65]
Is it possible to embed gif to AUK ?

**Comment by evgenyneu** [comment]
Hi @shanmarkus, yes, Auk supports gif images. Animation in the animated gifs will not work, it will only show the first frame.

**Comment by shanmarkus** [comment]
Hi @evgenyneu thank you for replying, is it possible to make it animated ? 

Cheers

**Comment by evgenyneu** [comment]
Good question. Auk uses standard `UIImageView` to show images, and, as far as I know, it does not support animation in gifs. It would probably be hard to implement it, unless someone shows me an easy way. :)

**Comment by shanmarkus** [comment]
Yep. No worries then, thank you so much for your reply. 😃
