### ISSUE TITLE
How to implement pinch to zoom?

### ISSUE THREAD

**Issue by 0x6d6e** [evgenyneu/Auk#66]
Hello Evgenii,
Thanks for this wonderful piece of work. I have enjoyed using this. 
I actually wanted to add "pinch to zoom" feature in this for my project. In your opinion, what would be the best approach to do on the Auk project?

Regards
Mithun

**Comment by evgenyneu** [comment]
Thanks, @0x6d6e. I would implement it in a separate scroll view containing single image:

1. User taps an image they want to view in Auk.
2. A new scroll view is shown with single image.
3. Use a pinch to zoom technique for single images, [here](https://github.com/evgenyneu/ios-imagescroll-swift) is an example of one.

**Comment by 0x6d6e** [comment]
THanks. Will check it out.
