### ISSUE TITLE
Value of type 'UIScrollView' has no member 'auk'

### ISSUE THREAD

**Issue by HideCode7** [evgenyneu/Auk#68]
* Library setup method: CocoaPods 
* Version of the library: 7.0
* Xcode version. Example: 8.3.3 
* OS version: iOS 9.0

When i build and run my app i don´t have any problems, but when i archive i have this error

Value of type 'UIScrollView' has no member 'auk'.

Somebody help me. 
Thank you and good work

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. It looks like it has not included the Auk library into the build. This is wierd. 

I would try other [setup methods](https://github.com/evgenyneu/Auk#setup) (file or carthage) to include Auk library and see if archiving works.

I've also created a demo app that uses Auk with CocoaPods for your reference, it archives without errors:

[DemoAuk.zip](https://github.com/evgenyneu/Auk/files/1171976/DemoAuk.zip)

Let me know how it goes.

**Comment by HideCode7** [comment]
Than you for the quick response. In my projecto in Pod in folder Frameworks i have the "moa.framework" in red.

My podfile like this

platform :ios, '9.0'
use_frameworks!

target 'myAppName' do
    pod 'Alamofire', '~> 4.0'
    pod 'PayPal-iOS-SDK', '~> 2.12.0'
    pod 'moa', '~> 8.0' 
    pod 'Auk', '~> 7.0'
    pod 'AZSClient'
end

**Comment by evgenyneu** [comment]
Your podfile looks good. I have no idea why it is happening, sorry. :(

**Comment by HideCode7** [comment]
I will try to add the files in my project and remove the pod auk and moa

**Comment by evgenyneu** [comment]
Wonderful, let me know if it helps.

**Comment by HideCode7** [comment]
I tried Carthage, and i have the same result. I guess this problem is the configuration, you dont´t have any idea? i tried archive your demo and i have sucess :).

**Comment by evgenyneu** [comment]
Interesting. No, I don't know what's going on. I've never seen such an issue before.

**Comment by HideCode7** [comment]
I found the solution, and it is remove auk and moa in my pod and add files in my project. Thanks you for this project and go on :)

**Comment by evgenyneu** [comment]
I'm glad it worked. It's still weird that it did not archive with CocoaPods installation. If anyone finds out why, please feel free to share. :)
