### ISSUE TITLE
Show more than an image

### ISSUE THREAD

**Issue by viciopoli01** [evgenyneu/Auk#69]
I'm trying to show an array of URLs ,but it doesn't work... 
The code I use is

for url in urls {
    SCR.sfrollview.show(URL: url)
}

**Comment by evgenyneu** [comment]
Hi @viciopoli01, thanks for reporting. That's weird, your code looks alright. Can you post your URLs here so I can test?

**Comment by viciopoli01** [comment]
Hi @evgenyneu the URLs are:
`ulrs=["https://img.iobii.com/4ae/d31/4aed31cfd1bdd532d6d4133b8acc1936-ar.jpg","https://img.iobii.com/e7f/ffd/e7fffd6d564f42b3819c32a2cf503393-ar.jpg",https://img.iobii.com/029/109/0291091f6d68e71aac5dc559af424530-ar.jpg]`

theese urls are utogenerated by an algorithm so usually are more than 3.

**Comment by evgenyneu** [comment]
Thanks for the URLs. I could not reproduce your problem, see the attached demo app. Maybe I am missing something?

[DoAuk.zip](https://github.com/evgenyneu/Auk/files/1528954/DoAuk.zip)

**Comment by viciopoli01** [comment]
Yes! The project works, it was a problem of urls ! Thanks
