### ISSUE TITLE
Preloading images

### ISSUE THREAD

**Issue by agfa555** [evgenyneu/Auk#8]
Hi,

I want to use your plugin in a new iOS App and I was wondering if there's any way of preloading the images before you change from one page to the other. I don't seem to find any option either in Auk or Moa. Is that posiible?

Thank you!

**Comment by evgenyneu** [comment]
Hi, no, unfortunately preloading images is not possible at the moment. Right now the image starts loading the moment it scrolled into view. It would be a nice feature to add in the future to allow the next image to preload before it is shown. Thanks for the idea.

**Comment by agfa555** [comment]
No problem. Thank you for the plugin.

**Comment by evgenyneu** [comment]
The image preload settings has been implemented.

```Swift
// Set the property before showing remote images
scrollView.auk.settings.preloadRemoteImagesAround = 1
```

More info here: https://github.com/evgenyneu/Auk#preloading-remote-images

**Comment by agfa555** [comment]
Working like a charm!!!!
Thanks a lot!!!
