### ISSUE TITLE
Loop to first image with animation going forward

### ISSUE THREAD

**Issue by sdavidliu** [evgenyneu/Auk#85]
Hi, I realized Auk is using a scroll view to loop through the photos. When it reaches the last photo, it loops back to the first photo by scrolling all the way back to index 0 while passing through all the photos in between. I was wondering if there was a way to have to same slide-to-the-left animation when going from the last photo back to the first photo.

**Comment by evgenyneu** [comment]
Hi @sdavidliu, good question. No, unfortunately, there is no way to transition from the last to the first image without showing all other images in-between currently.

**Comment by sdavidliu** [comment]
Ok just wondering! Thanks!
