### ISSUE TITLE
Page Control animation lost when using viewcontroller as delegate

### ISSUE THREAD

**Issue by benmoadw** [evgenyneu/Auk#86]
* Library setup method: CocoaPods.
* Version of the library. Example: 8.0.
* Xcode version. Example: 11.2
* OS version. Example: iOS 13.2

Hey! amazing library, been using it for quite a while now.

I just happen to have this weird behavior when I use a ViewController as the delegate for the Auk scrollviews the page control stop animating it stays in the first one and it doesn't move even tho I have multiple images loaded in the scrollview.

Help on this will be much appreciate.

**Comment by evgenyneu** [comment]
Thanks for reporting the issue, @benmoadw. Are you assigning the delegate **before** calling the `show` method? 

https://github.com/evgenyneu/Auk#page-control-is-not-changing--second-remote-image-is-not-shown

**Comment by benmoadw** [comment]
Welp! that was an ez one.

Thank you very much. it's solved!

**Comment by evgenyneu** [comment]
I'm glad it helped. 👍  Closing the issue. Feel free to reopen of your still have this problem.
