### ISSUE TITLE
How to hide page control?

### ISSUE THREAD

**Issue by cliff357** [evgenyneu/Auk#88]
Library setup method: CocoaPods
Version of the library.
'moa', 12
'Auk', 11
Xcode version. : 11.5
OS version.: iOS 13.5.1

Hello, i want to hide page control, but unfortunately 
"scrollView.auk.settings.pageControl.visible = false" not work 

Please kindly help :)

**Comment by evgenyneu** [comment]
Hi, thanks for reporting the issue. Do you set `pageControl.visible = false` before you calling the `show` method? For example:

```
scrollView.auk.settings.pageControl.visible = false
scrollView.auk.show(image: image)
```

**Comment by cliff357** [comment]
oh, i call it after the show. 
Should i call it before the show?

**Comment by evgenyneu** [comment]
Yes, `pageControl.visible = false` needs to be set before calling `show`.

**Comment by cliff357** [comment]
success! thank you very much
