### ISSUE TITLE
The request timed out Error for large images (5MB)

### ISSUE THREAD

**Issue by csprasad** [evgenyneu/Auk#89]
Im trying to show images using url which in response it contains 5 mb image file and always its throwing time out message.

**Comment by evgenyneu** [comment]
Thanks for reporting the issue. It could timeout because it takes longer than 20 seconds (default timeout) to load the large image. Maybe try increasing the timeout and see if it helps?

```
import moa
Moa.settings.requestTimeoutSeconds = 60
```

**Comment by csprasad** [comment]
Thank you @evgenyneu
